version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: docker/go/Dockerfile
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - ./:/usr/src/api/
    depends_on:
      - postgres          
    networks:
      - backend


  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #   networks:
  #     - backend
  #   restart: unless-stopped

volumes:
  api:
  postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
