version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: docker/go/Dockerfile
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - ./:/usr/src/api/
    depends_on:
      - postgres          
    networks:
      - backend


  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

volumes:
  api:
  postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
